version: "3.9"
services:
  api:
    build: .
    ports:
      - "${API_PORT}:8000"
    depends_on:
      mongo_db:
        condition: service_started
      redis:
        condition: service_healthy
      ngrok:
        condition: service_started
    container_name: pocket_assistant_api
    env_file:
      - .env
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        uvicorn app:app --host 0.0.0.0 --port 8000
    restart: on-failure

  mongo_db:
    image: mongo
    container_name: mongo_db
    env_file:
      - .env
    ports:
      - '${MONGO_EXPOSE_PORT}:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    ports:
      - "${REDIS_EXPOSE_PORT}:${REDIS_PORT}"
    container_name: redis
    restart: on-failure
    healthcheck:
      test: redis-cli -p ${REDIS_PORT} ping | grep PONG
      interval: 3s
      timeout: 2s
      retries: 3
    command: redis-server --save 20 1 --loglevel warning --port ${REDIS_PORT}
    volumes:
      - cache:/data

  ngrok:
    image: ngrok/ngrok
    container_name: ngrok
    env_file:
      - .env
    restart: on-failure
    command: http --domain=${TG_WEBHOOK_PROXY_NGROK_DOMAIN} ${API_HOST}:${API_PORT}

volumes:
  mongo_data:
  cache:
