PI_BUTTON_LAST_SENSORS_DATA: str = "LAST_SENSOR_DATA"

PI_BUTTON_SENSORS_ITEM_EMPTY: str = "empty"
PI_BUTTON_NO_LAST_SENSORS_DATA: str = "No data"

PI_BUTTON_TASK_PREFIX: str = "RUN"
PI_TASK_APPLIED_PART_MSG: str = "applied"
