name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name:  Create .env File
        env:
          ENV_PATH: ${{ vars.ENV_FILE_NAME }}
        run: |
          echo "DEBUG=${{ vars.DEBUG }}" >> $ENV_PATH
      - name: Test Linting
        run: make gha_ci_check_linting
      - name: Run Tests
        run: make gha_ci_test
